/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Z5yofKbwErb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function Home() {
  return (
    <div className="min-h-screen bg-black text-white p-4">
      <header className="flex items-center justify-between mb-8">
        <div className="flex items-center space-x-2">
          <LogInIcon className="w-8 h-8" />
          <span className="text-xl font-bold">AIHub</span>
        </div>
        <nav className="flex space-x-4">
          <Link href="#" className="text-white" prefetch={false}>
            Discover
          </Link>
          <Link href="#" className="text-white" prefetch={false}>
            Favorites
          </Link>
          <Button className="bg-teal-500 text-black">Submit</Button>
        </nav>
      </header>
      <main className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-yellow-500 p-6 rounded-lg flex flex-col justify-between">
          <div>
            <h2 className="text-3xl font-bold mb-4">Introducing Whisper</h2>
            <div className="w-full h-48 bg-black rounded-full" />
          </div>
          <div className="flex items-center space-x-2 mt-4">
            <MegaphoneIcon className="w-4 h-4" />
            <span className="text-sm">Whisper</span>
            <span className="text-sm text-gray-700">— Speech Recognition</span>
          </div>
        </div>
        <div className="space-y-4">
          <div className="bg-teal-500 p-6 rounded-lg">
            <div className="flex items-center justify-between">
              <Tally4Icon className="w-8 h-8" />
              <span className="text-3xl font-bold">95.5+</span>
            </div>
            <p className="mt-4">Introducing GPT-4, OpenAI's most advanced system</p>
            <Link href="#" className="text-white mt-4 block" prefetch={false}>
              Check it out
            </Link>
          </div>
          <div className="bg-pink-500 p-6 rounded-lg">
            <div className="flex items-center justify-between">
              <span className="text-sm bg-white text-black px-2 py-1 rounded-full">What's new?</span>
            </div>
            <h3 className="text-2xl font-bold mt-4">Can AI really be protected from text-based attacks?</h3>
          </div>
        </div>
        <div className="bg-white text-black p-6 rounded-lg">
          <img src="/placeholder.svg" alt="DallE-2" className="w-full h-48 object-cover rounded-lg mb-4" />
          <h3 className="text-2xl font-bold mb-4">DallE-2</h3>
          <ul className="space-y-2">
            <li className="flex justify-between">
              <span>ChatGPT</span>
              <span className="text-gray-500">/ search engine</span>
              <ArrowLeftIcon className="w-4 h-4" />
            </li>
            <li className="flex justify-between">
              <span>DALL-E</span>
              <span className="text-gray-500">/ image generator</span>
              <ArrowLeftIcon className="w-4 h-4" />
            </li>
            <li className="flex justify-between">
              <span>Whisper</span>
              <span className="text-gray-500">/ speech recognition</span>
              <ArrowLeftIcon className="w-4 h-4" />
            </li>
          </ul>
        </div>
      </main>
      <footer className="mt-8">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[50px]">#</TableHead>
              <TableHead>Name</TableHead>
              <TableHead>Category</TableHead>
              <TableHead>Price</TableHead>
              <TableHead>Type</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>01</TableCell>
              <TableCell className="flex items-center space-x-2">
                <WebcamIcon className="w-4 h-4" />
                <span>ChatGPT</span>
              </TableCell>
              <TableCell>Search Engine</TableCell>
              <TableCell>$20/mo</TableCell>
              <TableCell>Freemium</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>02</TableCell>
              <TableCell className="flex items-center space-x-2">
                <FingerprintIcon className="w-4 h-4" />
                <span>Fliki</span>
              </TableCell>
              <TableCell>Video Generator</TableCell>
              <TableCell>$8/mo</TableCell>
              <TableCell>Freemium</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>03</TableCell>
              <TableCell className="flex items-center space-x-2">
                <LollipopIcon className="w-4 h-4" />
                <span>Namelix</span>
              </TableCell>
              <TableCell>Business Name</TableCell>
              <TableCell>Startup tools</TableCell>
              <TableCell>Free</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>04</TableCell>
              <TableCell className="flex items-center space-x-2">
                <WavesIcon className="w-4 h-4" />
                <span>Writesonic</span>
              </TableCell>
              <TableCell>SEO Content</TableCell>
              <TableCell>$12.67/mo</TableCell>
              <TableCell>Freemium</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>05</TableCell>
              <TableCell className="flex items-center space-x-2">
                <TabletsIcon className="w-4 h-4" />
                <span>Tome</span>
              </TableCell>
              <TableCell>Story Teller</TableCell>
              <TableCell>Startup tools</TableCell>
              <TableCell>Free</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </footer>
    </div>
  )
}

function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function FingerprintIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 10a2 2 0 0 0-2 2c0 1.02-.1 2.51-.26 4" />
      <path d="M14 13.12c0 2.38 0 6.38-1 8.88" />
      <path d="M17.29 21.02c.12-.6.43-2.3.5-3.02" />
      <path d="M2 12a10 10 0 0 1 18-6" />
      <path d="M2 16h.01" />
      <path d="M21.8 16c.2-2 .131-5.354 0-6" />
      <path d="M5 19.5C5.5 18 6 15 6 12a6 6 0 0 1 .34-2" />
      <path d="M8.65 22c.21-.66.45-1.32.57-2" />
      <path d="M9 6.8a6 6 0 0 1 9 5.2v2" />
    </svg>
  )
}


function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}


function LollipopIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
      <path d="M11 11a2 2 0 0 0 4 0 4 4 0 0 0-8 0 6 6 0 0 0 12 0" />
    </svg>
  )
}


function MegaphoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 11 18-5v12L3 14v-3z" />
      <path d="M11.6 16.8a3 3 0 1 1-5.8-1.6" />
    </svg>
  )
}


function TabletsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="7" cy="7" r="5" />
      <circle cx="17" cy="17" r="5" />
      <path d="M12 17h10" />
      <path d="m3.46 10.54 7.08-7.08" />
    </svg>
  )
}


function Tally4Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 4v16" />
      <path d="M9 4v16" />
      <path d="M14 4v16" />
      <path d="M19 4v16" />
    </svg>
  )
}


function WavesIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
      <path d="M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
      <path d="M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
    </svg>
  )
}


function WebcamIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="10" r="8" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 22h10" />
      <path d="M12 22v-4" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
