/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/e42NbUPFNrl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function Page2() {
  return (
    <div className="flex flex-wrap min-h-screen">
      <div className="flex flex-col w-full p-6 space-y-8 bg-[#00bfa5] md:w-1/4">
        <h1 className="text-3xl font-bold text-white">Generative AI Tools</h1>
        <div className="flex justify-center">
          <GlobeIcon className="w-24 h-24 text-white" />
        </div>
        <div className="space-y-4 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-lg font-bold">01</p>
              <p className="text-lg font-semibold">Gen-2</p>
              <p className="text-sm">Turn any image, video clip or text</p>
            </div>
            <ArrowRightIcon className="w-6 h-6" />
          </div>
          <div className="flex items-center justify-between">
            <div>
              <p className="text-lg font-bold">02</p>
              <p className="text-lg font-semibold">Motion Tracking</p>
              <p className="text-sm">Automatically track the movement</p>
            </div>
            <ArrowRightIcon className="w-6 h-6" />
          </div>
          <div className="flex items-center justify-between">
            <div>
              <p className="text-lg font-bold">03</p>
              <p className="text-lg font-semibold">Green Screen</p>
              <p className="text-sm">Remove the background from video</p>
            </div>
            <ArrowRightIcon className="w-6 h-6" />
          </div>
          <div className="flex items-center justify-between">
            <div>
              <p className="text-lg font-bold">04</p>
              <p className="text-lg font-semibold">Inpainting</p>
              <p className="text-sm">Remove any object from any video</p>
            </div>
            <ArrowRightIcon className="w-6 h-6" />
          </div>
        </div>
      </div>
      <div className="flex flex-col w-full p-6 space-y-4 bg-white md:w-1/4">
        <h2 className="text-xl font-bold">Generate Videos</h2>
        <div className="flex items-center justify-between">
          <img src="/placeholder.svg" alt="Generate Videos" className="w-full h-12" />
          <p className="text-sm text-gray-500">Try Gen-1</p>
        </div>
        <h2 className="text-xl font-bold">Generate Images</h2>
        <div className="flex items-center justify-between">
          <img src="/placeholder.svg" alt="Generate Images" className="w-full h-12" />
          <p className="text-sm text-gray-500">Try Text to image</p>
        </div>
        <h2 className="text-xl font-bold">Slow Mo</h2>
        <div className="flex items-center justify-between">
          <img src="/placeholder.svg" alt="Slow Mo" className="w-full h-12" />
          <p className="text-sm text-gray-500">Try Super-slow</p>
        </div>
      </div>
      <div className="flex flex-col items-center justify-center w-full p-6 bg-[#004d40] md:w-1/4">
        <h2 className="text-3xl font-bold text-white">Everything you need to make anything you want!</h2>
        <Button className="mt-4" variant="default">
          Gen-1 now available
        </Button>
      </div>
      <div className="flex flex-col w-full p-6 space-y-4 bg-[#00bfa5] md:w-1/4">
        <div className="flex items-center justify-between">
          <LogInIcon className="w-8 h-8 text-white" />
          <p className="text-sm text-white">/runway</p>
        </div>
        <h2 className="text-4xl font-bold text-white">Gen-2 by Runway</h2>
        <div className="flex space-x-2">
          <img src="/placeholder.svg" alt="Image 1" className="w-16 h-16" />
          <img src="/placeholder.svg" alt="Image 2" className="w-16 h-16" />
          <img src="/placeholder.svg" alt="Image 3" className="w-16 h-16" />
        </div>
        <p className="text-sm text-white">
          Runway is a new kind of creative suite. One where AI is a collaborator and anything you can imagine can be
          created.
        </p>
        <Button className="mt-4" variant="default">
          Explore All AI Magic Tools
        </Button>
      </div>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function GlobeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  )
}


function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
